server.port: 9000
spring:
  application.name: security

authorization.server.url: http://weather-cloud-security:${server.port}
gateway.server.url: http://gateway:8080
weatherapi.server:
  host: weather-cloud-api
  port: 9090
